export const TASKS = [
  // ── BLOCK 1: 3% each (30 tasks = 90%) ──────────────────────────────────
  {
    id: "t01",
    group: "Connectivity",
    label: "Bi-Directional Connectivity",
    direction: null,
    messageType: null,
    scenario: "setup",
    weight: 3,
  },
  {
    id: "t02",
    group: "ACMT / PACS Basic",
    label: "ACMT023 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "ACMT023",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t03",
    group: "ACMT / PACS Basic",
    label: "PACS008 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PACS008",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t04",
    group: "ACMT / PACS Basic",
    label: "PACS028 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PACS028",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t05",
    group: "ACMT / PACS Basic",
    label: "GetParticipant",
    direction: "FI→NIBSS",
    messageType: "GETPARTICIPANT",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t06",
    group: "ACMT / PACS Basic",
    label: "ACMT023 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "ACMT023",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t07",
    group: "ACMT / PACS Basic",
    label: "PACS008 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PACS008",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t08",
    group: "ACMT / PACS Negative",
    label: "ACMT023 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "ACMT023",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t09",
    group: "ACMT / PACS Negative",
    label: "ACMT023 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "ACMT023",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t10",
    group: "ACMT / PACS Negative",
    label: "PACS008 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PACS008",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t11",
    group: "ACMT / PACS Negative",
    label: "PACS008 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PACS008",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t12",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "PAIN009 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PAIN009",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t13",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "PAIN010 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PAIN010",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t14",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "PAIN011 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PAIN011",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t15",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "PAIN013 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PAIN013",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t16",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "PACS003 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "PACS003",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t17",
    group: "PAIN / PACS / CAMT – FI→NIBSS",
    label: "CAMT060 – FI → NIBSS",
    direction: "FI→NIBSS",
    messageType: "CAMT060",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t18",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "PAIN009 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PAIN009",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t19",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "PAIN010 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PAIN010",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t20",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "PAIN011 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PAIN011",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t21",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "PAIN013 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PAIN013",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t22",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "PACS003 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "PACS003",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t23",
    group: "PAIN / PACS / CAMT – NIBSS→FI",
    label: "CAMT060 – NIBSS → FI",
    direction: "NIBSS→FI",
    messageType: "CAMT060",
    scenario: "positive",
    weight: 3,
  },
  {
    id: "t24",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "PAIN009 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PAIN009",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t25",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "PAIN010 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PAIN010",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t26",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "PAIN011 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PAIN011",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t27",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "PAIN013 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PAIN013",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t28",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "PACS003 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "PACS003",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t29",
    group: "PAIN / PACS / CAMT – FI→NIBSS Negative",
    label: "CAMT060 – FI → NIBSS (negative)",
    direction: "FI→NIBSS",
    messageType: "CAMT060",
    scenario: "negative",
    weight: 3,
  },
  {
    id: "t30",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "PAIN009 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PAIN009",
    scenario: "negative",
    weight: 3,
  },

  // ── BLOCK 2: 2% each (5 tasks = 10%) ───────────────────────────────────
  {
    id: "t31",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "PAIN010 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PAIN010",
    scenario: "negative",
    weight: 2,
  },
  {
    id: "t32",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "PAIN011 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PAIN011",
    scenario: "negative",
    weight: 2,
  },
  {
    id: "t33",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "PAIN013 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PAIN013",
    scenario: "negative",
    weight: 2,
  },
  {
    id: "t34",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "PACS003 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "PACS003",
    scenario: "negative",
    weight: 2,
  },
  {
    id: "t35",
    group: "PAIN / PACS / CAMT – NIBSS→FI Negative",
    label: "CAMT060 – NIBSS → FI (negative)",
    direction: "NIBSS→FI",
    messageType: "CAMT060",
    scenario: "negative",
    weight: 2,
  },
];

export const TOTAL_WEIGHT = TASKS.reduce((s, t) => s + t.weight, 0); // must be 100

export const TASK_GROUPS = [...new Set(TASKS.map((t) => t.group))];

export function computeScore(taskStatuses) {
  // taskStatuses: { [taskId]: "pending" | "pass" | "fail" | "blocked" }
  return TASKS.reduce((score, task) => {
    const status = taskStatuses[task.id] || "pending";
    return status === "pass" ? score + task.weight : score;
  }, 0);
}

export function groupedTasks() {
  return TASK_GROUPS.map((group) => ({
    group,
    tasks: TASKS.filter((t) => t.group === group),
    totalWeight: TASKS.filter((t) => t.group === group).reduce(
      (s, t) => s + t.weight,
      0
    ),
  }));
}
